import { LOADING_END, LOADING_START } from "./loading";
import {SAVE_BLOG,INITIAL_BLOG} from './save-blog'
//登录登出
const REQUEST_LOGIN = "REQUEST_LOGIN";
const RECEIVE_LOGIN = "RECEIVE_LOGIN";
const REQUEST_LOGOUT = "REQUEST_LOGOUT";
const RECEIVE_LOGOUT = "RECEIVE_LOGOUT";
export {
  REQUEST_LOGIN,
  RECEIVE_LOGIN,
  REQUEST_LOGOUT,
  RECEIVE_LOGOUT,
  LOADING_END,
  LOADING_START,
  SAVE_BLOG,
  INITIAL_BLOG
};
//改变header的router
export const CHANGEROUTER = "CHANGEROUTER";
export const INITIAL = "INITIAL";
